using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookingDet
{
    public class BookingDetail
    {
        /*
        /*
        /*BookingID(Autogenerated , starting from 5000) Name Age Contact Number Email Id Address Room Category(single,double,Deluxe) Number of Days Rental Amount(No need to get this field from the user, need to calculate)

        */
        int booking_id;
        string name;
        int age;
        long contact_num;
        string email_id;
        string address;
        string roomcategory;
        int number_of_days;
        int rental_amount;

        public BookingDetail( string name, int age, long contact_num, string email_id, string address, string roomcategory, int number_of_days)
        {
            //this.booking_id = booking_id;
            this.name = name;
            this.age = age;
            this.contact_num = contact_num;
            this.email_id = email_id;
            this.address = address;
            this.roomcategory = roomcategory;
            this.number_of_days = number_of_days;
            if(roomcategory=="Single")
            this.rental_amount = number_of_days* 1000;
            if (roomcategory == "Double")
                this.rental_amount = number_of_days * 2500;
            if (roomcategory == "Deluxe")
                this.rental_amount = number_of_days * 5000;
        }
        public BookingDetail()
        {

        }

        public int Booking_id
        {
            get
            {
                return booking_id;
            }

            set
            {
                booking_id = value;
            }
        }

        public string Name
        {
            get
            {
                return name;
            }

            set
            {
                name = value;
            }
        }

        public int Age
        {
            get
            {
                return age;
            }

            set
            {
                age = value;
            }
        }

        public long Contact_num
        {
            get
            {
                return contact_num;
            }

            set
            {
                contact_num = value;
            }
        }

        public string Email_id
        {
            get
            {
                return email_id;
            }

            set
            {
                email_id = value;
            }
        }

        public string Address
        {
            get
            {
                return address;
            }

            set
            {
                address = value;
            }
        }

        public string Roomcategory
        {
            get
            {
                return roomcategory;
            }

            set
            {
                roomcategory = value;
            }
        }

        public int Number_of_days
        {
            get
            {
                return number_of_days;
            }

            set
            {
                number_of_days = value;
            }
        }

        public int Rental_amount
        {
            get
            {
                return rental_amount;
            }

            set
            {
                rental_amount = value;
            }
        }
    }
}
